title: メクルン
copy: スライドで学べるビジュアルプログラミング学習サービス Mekurun [メクルン]
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin
  - jekyll-minifier

languages: ["ja", "en", "kana"]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:title/

collections:
  courses:
    output: true
  categories:
    output: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
