title: メクルン
description: メクルン (Mekurun) はスライドで学べるビジュアルプログラミング学習サービスです。ScratchやMakeCodeといったブロックでプログラミングができるビジュアルプログラミング言語を中心に子ども向けのプログラミング入門コンテンツを提供しています。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mekurun.com" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
markdown: MekurunCustomConverter
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin
  - jekyll-minifier

languages: ["ja", "en", "kana"]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:title/

collections:
  courses:
    output: true
  categories:
    output: true
    order:
      - scratch.md
      - minecraft.md

pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "**/*.{js,css,eot,svg,jpg,jpeg,png,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"


jekyll-minifier:
  compress_javascript: false

exclude:
  - src
  - .jekyll-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
